version: '3.8'

services:
  pereiratechtalks: &pereiratechtalks
    build:
      context: .
      dockerfile: ./pereiratechtalks/Dockerfile
    working_dir: /app
    volumes:
      - ../..:/app
    ports:
      - '4333:4321'
      - '8999:8969'
    env_file:
      - pereiratechtalks/.env
    command:
      - /bin/sh
      - -c
      - |
        sleep infinity
