name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Step 1 - 🧪 Run linter
      run: |
        npm install
        npm ci --ignore-scripts
        npm run lint
    - name: Step 2 - 🛠️ Build application bundle
      run: |
        pwd
        ls -la 
        ls -la node_modules/.bin/
        cd ~
        pwd
        ls -la 
        find . -type d -name "hugo" 
        npm run build
    - name: Step 3 - 📄 Deploy to GitHub Pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}