name: Deploy changes into GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']
    steps:
      - name: Step 1 - ⚙️ Setup GitHub Config
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Step 2 - ⚙️ Setup GitHub Config
        run: |
          git config user.name "🤖 Pereira Tech Talks"
          git config user.email "pereiratechtalks@gmail.com"
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Step 3 - 📁 Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Step 4 - ⚙️ Install Dependencies
        run: npm install
      - name: Step 5 - Verify the existence of 'main_ghpages' branch
        run: |
          git checkout -b main_ghpages
          git pull origin main_ghpages
      - name: Step 6 - Push changes to main_ghpages
        run: |
          git push origin main_ghpages
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
