name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Step 1 - 🛠️ Build application bundle
      run: |
        npm install
        npm ci --ignore-scripts
        npm run lint
        npm run build
    - name: Step 2 - 📄 Deploy to GitHub Pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}