name: Validations Pre-Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          path: website
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
      - name: Install node dependencies
        run: |
          cd website
          yarn install --ignore-engines
      - name: Show node environment
        run: |
          node --version
          npm --version
          yarn --version
      - name: Run Formatter
        run: |
          cd website
          yarn prettier:check
      - name: Run Linter
        run: |
          cd website
          yarn eslint:check

  build:
    name: Build
    needs: [format]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          path: website
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
      - name: Install node dependencies
        run: |
          cd website
          yarn install --ignore-engines
      - name: Show node environment
        run: |
          node --version
          npm --version
          yarn --version
      - name: Build static files
        run: |
          cd website
          yarn build
